sudo: required
services:
  - docker
  
before_install:
  - docker build -t thomasreuss/docker-react -f Dockerfile.dev .
  
script:
  - docker run -e CI=true thomasreuss/docker-react npm run test
  
deploy:
  provider: elasticbeanstalk
  region: "eu-central-1"
  name: "docker-react"
  env: "DockerReact2-env"
  bucket_name: "elasticbeanstalk-eu-central-1-489316658924"
  bucket_path: "docker-react2"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  